name: Deploy to Server
on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: install npm
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - name: Copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "./build"
          target: ${{ secrets.COPY_TO }}

